import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import QueryProvider from "@/lib/providers/QueryProvider";
// import { useAuthCheck } from "@/lib/hooks/useAuthCheck";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useAuthCheck()
  return (
    <html lang="ru">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
      <body>
        <Header />
        <main>
          <QueryProvider>{children}</QueryProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
