import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import QueryProvider from "@/lib/providers/QueryProvider";
// import { useAuthCheck } from "@/lib/hooks/useAuthCheck";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useAuthCheck()
  return (
    <html lang="en">
      <script
          async
          src="https://cdn.userway.org/widget.js"
          data-account="ВАШ_API_КЛЮЧ"
        ></script>
      <body>
        <Header />
        <main>
          <QueryProvider>{children}</QueryProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
