import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import QueryProvider from "@/lib/providers/QueryProvider";
import { useAuthCheck } from "@/lib/hooks/useAuthCheck";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useAuthCheck()
  return (
    <html lang="en">
      <body className=" bg-amber-50">
       <Header/>
       <main className='container mx-auto'>
        <QueryProvider>{children}</QueryProvider>
       </main>
      </body>
    </html>
  );
}
